/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/routes/__root'
import { Route as GuestLayoutImport } from './app/routes/_guest-layout'
import { Route as GuestLayoutPolicyImport } from './app/routes/_guest-layout/policy'
import { Route as GuestLayoutFiltrationImport } from './app/routes/_guest-layout/filtration'
import { Route as GuestLayoutAboutImport } from './app/routes/_guest-layout/about'
import { Route as GuestLayoutHomeIndexImport } from './app/routes/_guest-layout/_home.index'
import { Route as GuestLayoutCompareIdsImport } from './app/routes/_guest-layout/compare.$ids'
import { Route as GuestLayoutCarsCarIdImport } from './app/routes/_guest-layout/cars.$car-id'

// Create/Update Routes

const GuestLayoutRoute = GuestLayoutImport.update({
  id: '/_guest-layout',
  getParentRoute: () => rootRoute,
} as any)

const GuestLayoutPolicyRoute = GuestLayoutPolicyImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => GuestLayoutRoute,
} as any)

const GuestLayoutFiltrationRoute = GuestLayoutFiltrationImport.update({
  id: '/filtration',
  path: '/filtration',
  getParentRoute: () => GuestLayoutRoute,
} as any)

const GuestLayoutAboutRoute = GuestLayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => GuestLayoutRoute,
} as any)

const GuestLayoutHomeIndexRoute = GuestLayoutHomeIndexImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => GuestLayoutRoute,
} as any)

const GuestLayoutCompareIdsRoute = GuestLayoutCompareIdsImport.update({
  id: '/compare/$ids',
  path: '/compare/$ids',
  getParentRoute: () => GuestLayoutRoute,
} as any)

const GuestLayoutCarsCarIdRoute = GuestLayoutCarsCarIdImport.update({
  id: '/cars/$car-id',
  path: '/cars/$car-id',
  getParentRoute: () => GuestLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest-layout': {
      id: '/_guest-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_guest-layout/about': {
      id: '/_guest-layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof GuestLayoutAboutImport
      parentRoute: typeof GuestLayoutImport
    }
    '/_guest-layout/filtration': {
      id: '/_guest-layout/filtration'
      path: '/filtration'
      fullPath: '/filtration'
      preLoaderRoute: typeof GuestLayoutFiltrationImport
      parentRoute: typeof GuestLayoutImport
    }
    '/_guest-layout/policy': {
      id: '/_guest-layout/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof GuestLayoutPolicyImport
      parentRoute: typeof GuestLayoutImport
    }
    '/_guest-layout/cars/$car-id': {
      id: '/_guest-layout/cars/$car-id'
      path: '/cars/$car-id'
      fullPath: '/cars/$car-id'
      preLoaderRoute: typeof GuestLayoutCarsCarIdImport
      parentRoute: typeof GuestLayoutImport
    }
    '/_guest-layout/compare/$ids': {
      id: '/_guest-layout/compare/$ids'
      path: '/compare/$ids'
      fullPath: '/compare/$ids'
      preLoaderRoute: typeof GuestLayoutCompareIdsImport
      parentRoute: typeof GuestLayoutImport
    }
    '/_guest-layout/_home/': {
      id: '/_guest-layout/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestLayoutHomeIndexImport
      parentRoute: typeof GuestLayoutImport
    }
  }
}

// Create and export the route tree

interface GuestLayoutRouteChildren {
  GuestLayoutAboutRoute: typeof GuestLayoutAboutRoute
  GuestLayoutFiltrationRoute: typeof GuestLayoutFiltrationRoute
  GuestLayoutPolicyRoute: typeof GuestLayoutPolicyRoute
  GuestLayoutCarsCarIdRoute: typeof GuestLayoutCarsCarIdRoute
  GuestLayoutCompareIdsRoute: typeof GuestLayoutCompareIdsRoute
  GuestLayoutHomeIndexRoute: typeof GuestLayoutHomeIndexRoute
}

const GuestLayoutRouteChildren: GuestLayoutRouteChildren = {
  GuestLayoutAboutRoute: GuestLayoutAboutRoute,
  GuestLayoutFiltrationRoute: GuestLayoutFiltrationRoute,
  GuestLayoutPolicyRoute: GuestLayoutPolicyRoute,
  GuestLayoutCarsCarIdRoute: GuestLayoutCarsCarIdRoute,
  GuestLayoutCompareIdsRoute: GuestLayoutCompareIdsRoute,
  GuestLayoutHomeIndexRoute: GuestLayoutHomeIndexRoute,
}

const GuestLayoutRouteWithChildren = GuestLayoutRoute._addFileChildren(
  GuestLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof GuestLayoutRouteWithChildren
  '/about': typeof GuestLayoutAboutRoute
  '/filtration': typeof GuestLayoutFiltrationRoute
  '/policy': typeof GuestLayoutPolicyRoute
  '/cars/$car-id': typeof GuestLayoutCarsCarIdRoute
  '/compare/$ids': typeof GuestLayoutCompareIdsRoute
  '/': typeof GuestLayoutHomeIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof GuestLayoutAboutRoute
  '/filtration': typeof GuestLayoutFiltrationRoute
  '/policy': typeof GuestLayoutPolicyRoute
  '/cars/$car-id': typeof GuestLayoutCarsCarIdRoute
  '/compare/$ids': typeof GuestLayoutCompareIdsRoute
  '/': typeof GuestLayoutHomeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_guest-layout': typeof GuestLayoutRouteWithChildren
  '/_guest-layout/about': typeof GuestLayoutAboutRoute
  '/_guest-layout/filtration': typeof GuestLayoutFiltrationRoute
  '/_guest-layout/policy': typeof GuestLayoutPolicyRoute
  '/_guest-layout/cars/$car-id': typeof GuestLayoutCarsCarIdRoute
  '/_guest-layout/compare/$ids': typeof GuestLayoutCompareIdsRoute
  '/_guest-layout/_home/': typeof GuestLayoutHomeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/filtration'
    | '/policy'
    | '/cars/$car-id'
    | '/compare/$ids'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/filtration'
    | '/policy'
    | '/cars/$car-id'
    | '/compare/$ids'
    | '/'
  id:
    | '__root__'
    | '/_guest-layout'
    | '/_guest-layout/about'
    | '/_guest-layout/filtration'
    | '/_guest-layout/policy'
    | '/_guest-layout/cars/$car-id'
    | '/_guest-layout/compare/$ids'
    | '/_guest-layout/_home/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  GuestLayoutRoute: typeof GuestLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  GuestLayoutRoute: GuestLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_guest-layout"
      ]
    },
    "/_guest-layout": {
      "filePath": "_guest-layout.tsx",
      "children": [
        "/_guest-layout/about",
        "/_guest-layout/filtration",
        "/_guest-layout/policy",
        "/_guest-layout/cars/$car-id",
        "/_guest-layout/compare/$ids",
        "/_guest-layout/_home/"
      ]
    },
    "/_guest-layout/about": {
      "filePath": "_guest-layout/about.tsx",
      "parent": "/_guest-layout"
    },
    "/_guest-layout/filtration": {
      "filePath": "_guest-layout/filtration.tsx",
      "parent": "/_guest-layout"
    },
    "/_guest-layout/policy": {
      "filePath": "_guest-layout/policy.tsx",
      "parent": "/_guest-layout"
    },
    "/_guest-layout/cars/$car-id": {
      "filePath": "_guest-layout/cars.$car-id.tsx",
      "parent": "/_guest-layout"
    },
    "/_guest-layout/compare/$ids": {
      "filePath": "_guest-layout/compare.$ids.tsx",
      "parent": "/_guest-layout"
    },
    "/_guest-layout/_home/": {
      "filePath": "_guest-layout/_home.index.tsx",
      "parent": "/_guest-layout"
    }
  }
}
ROUTE_MANIFEST_END */
